# Generated by Django 4.2.23 on 2025-06-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('URL', 'URL'), ('TEXT', 'Text'), ('PDF', 'PDF'), ('YOUTUBE', 'YouTube')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=100, unique=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('translation_tr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.source')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word')),
            ],
            options={
                'unique_together': {('word', 'source')},
            },
        ),
        migrations.AddField(
            model_name='word',
            name='sources',
            field=models.ManyToManyField(through='core.WordSourceLink', to='core.source'),
        ),
        migrations.CreateModel(
            name='UserWordKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('LEARNING', 'Learning'), ('KNOWN', 'Known'), ('IGNORED', 'Ignored')], default='NEW', max_length=10)),
                ('due', models.DateTimeField(db_index=True)),
                ('stability', models.FloatField(default=0)),
                ('difficulty', models.FloatField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_knowledge', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_knowledge', to='core.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
