# Generated by Django 4.2.23 on 2025-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordknowledge',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
