# Generated by Django 4.2.23 on 2025-06-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='known_threshold',
            field=models.PositiveIntegerField(default=5, help_text="Number of successful reviews needed before a word is considered 'known'"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='retention_rate',
            field=models.FloatField(default=0.9, help_text='Target retention rate (0.8-0.95)'),
        ),
        migrations.AddField(
            model_name='userwordknowledge',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwordknowledge',
            name='successful_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwordknowledge',
            name='difficulty',
            field=models.FloatField(default=5.0),
        ),
    ]
