# Generated by Django 4.2.23 on 2025-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_known_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('URL', 'URL'), ('TEXT', 'Text'), ('PDF', 'PDF'), ('YOUTUBE', 'YouTube'), ('EXTENSION', 'Extension')], max_length=10),
        ),
    ]
