# Generated by Django 4.2.23 on 2025-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Pro account status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pro_expiry_date',
            field=models.DateTimeField(blank=True, help_text='When Pro subscription expires', null=True),
        ),
    ]
