# Generated by Django 4.2.23 on 2025-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscription_billinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('URL', 'URL'), ('TEXT', 'Text'), ('PDF', 'PDF'), ('YOUTUBE', 'YouTube'), ('SRT', 'SRT Subtitles'), ('EXTENSION', 'Extension')], max_length=10),
        ),
    ]
