# Generated by Django 4.2.23 on 2025-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_new_word_target',
            field=models.PositiveIntegerField(default=20, help_text='Number of new words introduced per day (Pro customizable)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_learning_target',
            field=models.PositiveIntegerField(default=20, help_text='Total daily learning target (legacy)'),
        ),
    ]
