# Generated by Django 4.2.23 on 2025-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_daily_new_word_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filter_stop_words',
            field=models.BooleanField(default=True, help_text='Filter common English words (the, and, is, etc.) from priority ranking (Pro only)'),
        ),
    ]
