# Generated by Django 5.0.2 on 2025-02-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_dictionaryreport_dictionaryword_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_dictionary_word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='translation',
        ),
        migrations.AddField(
            model_name='word',
            name='dictionary_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_words', to='words.dictionaryword'),
        ),
    ]
