name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks and migrations
        env:
          DJANGO_SECRET_KEY: test-secret
          DJANGO_DEBUG: 'True'
        run: |
          python manage.py check
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DJANGO_SECRET_KEY: test-secret
          DJANGO_DEBUG: 'True'
        run: |
          python manage.py test --noinput


